import "server-only";

import type { ServiceOrderListItem, ServiceOrderRepository } from "@/modules/service-orders/domain/repositories/ServiceOrderRepository";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type Relation<T> = T | T[] | null;
const one = <T,>(value: Relation<T>): T | null => Array.isArray(value) ? value[0] ?? null : value;
const SELECT = "id,reception_id,order_number,opened_at,updated_at,service_order_statuses!inner(code,name,is_terminal),device_receptions!inner(reported_problem,created_at,customer_devices!inner(id,fk_cliente_id,numero_serie,customers!inner(first_name,last_name),device_types!inner(name),device_brands(name),device_models(name),device_colors(name)))";

type OrderRow = { id: string; reception_id: string; order_number: number | string; opened_at: string; updated_at: string; service_order_statuses: Relation<{ code: string; name: string; is_terminal: boolean }>; device_receptions: Relation<{ reported_problem: string; created_at: string; customer_devices: Relation<{ id: string; fk_cliente_id: string; numero_serie: string | null; customers: Relation<{ first_name: string | null; last_name: string | null }>; device_types: Relation<{ name: string }>; device_brands: Relation<{ name: string }>; device_models: Relation<{ name: string }>; device_colors: Relation<{ name: string }> }> }> };
function map(row: OrderRow): ServiceOrderListItem {
  const reception = one(row.device_receptions); const device = one(reception?.customer_devices); const customer = one(device?.customers); const type = one(device?.device_types); const brand = one(device?.device_brands); const model = one(device?.device_models); const color = one(device?.device_colors); const status = one(row.service_order_statuses);
  return { id: row.id, orderNumber: Number(row.order_number), receptionId: row.reception_id, status: { code: status?.code ?? "UNKNOWN", name: status?.name ?? "Sin estado", isTerminal: Boolean(status?.is_terminal) }, customerId: device?.fk_cliente_id ?? "", customerName: [customer?.first_name, customer?.last_name].filter(Boolean).join(" "), device: { id: device?.id ?? "", type: type?.name ?? "Dispositivo", brand: brand?.name ?? "Sin marca", model: model?.name ?? "Sin modelo", color: color?.name ?? undefined, serialNumber: device?.numero_serie ?? undefined }, reportedProblem: reception?.reported_problem ?? "", receivedAt: reception?.created_at ?? row.opened_at, updatedAt: row.updated_at };
}

export class SupabaseServiceOrderRepository implements ServiceOrderRepository {
  async createFromReception(input: { receptionId: string; priorityId?: string; complexityId?: string; notes?: string }) { const db = await createSupabaseServerClient(); const { data, error } = await db.rpc("create_service_order", { p_reception_id: input.receptionId, p_priority_id: input.priorityId ?? null, p_complexity_id: input.complexityId ?? null, p_notes: input.notes ?? null }); if (error || !data) throw new Error("SERVICE_ORDER_CREATE_FAILED"); return String(data); }
  async list() { const db = await createSupabaseServerClient(); const { data, error } = await db.from("service_orders").select(SELECT).order("opened_at", { ascending: false }); if (error) throw new Error("SERVICE_ORDERS_READ_FAILED"); return ((data ?? []) as unknown as OrderRow[]).map(map); }
  async getById(id: string) { const db = await createSupabaseServerClient(); const { data, error } = await db.from("service_orders").select(SELECT).eq("id", id).maybeSingle(); if (error) throw new Error("SERVICE_ORDER_READ_FAILED"); return data ? map(data as unknown as OrderRow) : null; }
  async listStatuses() { const db = await createSupabaseServerClient(); const { data, error } = await db.from("service_order_statuses").select("id,code,name,is_terminal").eq("is_active", true).order("sort_order"); if (error) throw new Error("SERVICE_ORDER_STATUSES_READ_FAILED"); return (data ?? []).map((row) => ({ id: row.id, code: row.code, name: row.name, isTerminal: row.is_terminal })); }
  async changeStatus(input: { orderId: string; statusCode: string; note?: string }) { const db = await createSupabaseServerClient(); const { error } = await db.rpc("change_service_order_status", { p_service_order_id: input.orderId, p_status_code: input.statusCode, p_note: input.note ?? null }); if (error) throw new Error("SERVICE_ORDER_STATUS_CHANGE_FAILED"); }
  async assignTechnician(input: { orderId: string; technicianUserId: string; assignmentRole?: string; primary?: boolean }) { const db = await createSupabaseServerClient(); const { data, error } = await db.rpc("assign_service_order_technician", { p_service_order_id: input.orderId, p_technician_user_id: input.technicianUserId, p_assignment_role: input.assignmentRole ?? "TECHNICIAN", p_primary: input.primary ?? false }); if (error || !data) throw new Error("SERVICE_ORDER_ASSIGNMENT_FAILED"); return String(data); }
  async unassignTechnician(assignmentId: string) { const db = await createSupabaseServerClient(); const { error } = await db.rpc("unassign_service_order_technician", { p_assignment_id: assignmentId }); if (error) throw new Error("SERVICE_ORDER_UNASSIGN_FAILED"); }
  async recordTime(input: { orderId: string; taskId?: string; startedAt: string; endedAt?: string; notes?: string }) { const db = await createSupabaseServerClient(); const { data, error } = await db.rpc("record_service_order_time", { p_service_order_id: input.orderId, p_task_id: input.taskId ?? null, p_started_at: input.startedAt, p_ended_at: input.endedAt ?? null, p_notes: input.notes ?? null }); if (error || !data) throw new Error("SERVICE_ORDER_TIME_ENTRY_FAILED"); return String(data); }
}
