import { ArrowRight, BadgeCheck, Bolt, Boxes, CheckCircle2, CircleDotDashed, Clock3, FileSearch, History, Mail, MapPin, MessageCircle, ShieldCheck, Smartphone, Wrench } from "lucide-react";
import type { Metadata } from "next";
import Image from "next/image";
import type { ComponentType } from "react";

import { PublicFooter } from "@/components/public/PublicFooter";
import { GitHubIcon } from "@/components/icons/GitHubIcon";
import { PublicNavbar } from "@/components/public/PublicNavbar";
import { RepairFlowDemo } from "@/components/public/RepairFlowDemo";
import { ButtonLink } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { brand } from "@/config/brand";

export const metadata: Metadata = {
  title: "Nodo | Home",
  description: "Nodo es una aplicación gratuita para gestionar órdenes, diagnósticos, aprobaciones, reparaciones y seguimiento de dispositivos de servicios técnicos.",
  alternates: { canonical: "/" },
  openGraph: { title: "Nodo | Sistema de gestión de reparaciones y servicios técnicos", description: "Organizá órdenes, diagnósticos, aprobaciones, repuestos y seguimiento de reparaciones en un mismo lugar.", images: [{ url: brand.assets.banner, alt: "Identidad visual de Nodo" }] },
};

const Github = GitHubIcon;

const features = [
  { icon: Bolt, title: "Acciones rápidas", description: "Las tareas repetidas crear una orden, registrar un diagnóstico, cambiar el estado que se encuentra el dispositivo, preparar un presupuesto o documentar una entrega requieren la menor cantidad posible de pasos. Menos carga administrativa significa más tiempo para reparar." },
  { icon: Clock3, title: "Seguimiento claro", description: "El cliente puede consultar qué está pasando sin depender constantemente de mensajes o llamadas. El técnico actualiza la reparación según sus propios tiempos y evita explicar el mismo estado varias veces." },
  { icon: FileSearch, title: "Diagnósticos documentados", description: "Cómo ingresó el dispositivo, qué fallas tenía, qué componentes se revisaron, qué reparación se propone y qué piezas se reemplazan pueden quedar registrados. Esa trazabilidad protege la confianza y reduce malos entendidos." },
  { icon: BadgeCheck, title: "Todo se aprueba", description: "Ninguna decisión importante se da por entendida. Presupuestos, cambios de piezas, ampliaciones del diagnóstico y gastos adicionales pueden conservar su aprobación antes de avanzar." },
  { icon: History, title: "Historial cuando lo necesitás", description: "Las órdenes anteriores ayudan a consultar fallas repetidas, componentes reemplazados, diagnósticos, presupuestos, fechas y observaciones durante el tiempo que el servicio técnico decida conservarlas." },
  { icon: Boxes, title: "Repuestos y disponibilidad", description: "Una orden puede relacionarse con repuestos disponibles, pendientes, por conseguir, solicitados o recibidos. Así, una reparación detenida mantiene su contexto y no parece simplemente olvidada." },
] as const;

const connectedItems = ["Cliente", "Dispositivo", "Recepción", "Diagnóstico", "Presupuesto", "Autorización", "Reparación", "Repuestos", "Seguimiento", "Entrega"];

export default function HomePage() {
  const structuredData = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Nodo", applicationCategory: "BusinessApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "ARS" }, description: "Plataforma gratuita de iniciativa independiente.", author: { "@type": "Person", name: "Lada Elizabet Rodriguez", jobTitle: "Software Developer | Web Application Development", address: { "@type": "PostalAddress", addressLocality: "Formosa", addressRegion: "Formosa", addressCountry: "AR" } } };
  return <div className="public-shell min-h-screen text-ink"><script dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} type="application/ld+json" /><PublicNavbar /><main>
    <section className="public-section public-container grid gap-12 py-15 sm:py-20 lg:grid-cols-[1.02fr_0.98fr] lg:items-center lg:py-22" id="inicio">
      <div className="public-enter"><p className="inline-flex items-center gap-2 rounded-full border border-line bg-accent-soft px-3 py-1.5 text-xs font-bold uppercase tracking-[0.14em] text-accent"><CircleDotDashed className="size-3.5" />Gestión conectada</p><h1 className="mt-5 max-w-2xl text-4xl font-bold leading-[1.07] tracking-tight sm:text-5xl lg:text-[3.55rem]">Reparaciones claras, <span className="text-accent">de principio a fin.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-ink-secondary sm:text-lg"><strong>Nodo</strong> conecta al servicio técnico con cada cliente durante todo el proceso: desde el ingreso del dispositivo hasta su diagnóstico, aprobación, reparación y entrega.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/register" size="lg">Crear mi cuenta <ArrowRight className="size-4" /></ButtonLink><a className="inline-flex min-h-12 items-center justify-center rounded-lg border border-line bg-surface px-5 text-sm font-semibold text-ink transition-colors hover:border-accent hover:bg-surface-soft" href="#como-funciona">Conocer cómo funciona</a></div><p className="mt-6 flex items-center gap-2 text-sm text-ink-secondary"><CheckCircle2 className="size-4 text-success" />Proyecto gratuito y sin fines de lucro.</p></div>
      <div className="public-enter-delay relative"><div className="node-grid absolute -inset-4 -z-10 rounded-[2rem] opacity-75" /><div className="overflow-hidden rounded-[1.5rem] border border-line bg-brand-surface p-2 shadow-[0_24px_70px_rgb(var(--shadow-color)/18%)]"><Image alt="Logo de Nodo con línea de diagnóstico, circuito y nodos conectados" className="h-auto w-full rounded-[1.05rem] object-cover" priority sizes="(min-width: 1024px) 560px, 100vw" src={brand.assets.banner} width={2048} height={640} /></div><div className="absolute -bottom-5 -left-2 hidden max-w-64 rounded-xl border border-line bg-surface-raised p-4 shadow-lg sm:block"><div className="flex items-center gap-2 text-xs font-bold text-ink"><ShieldCheck className="size-4 text-accent" />Información que conecta</div><p className="mt-2 text-xs leading-5 text-ink-secondary">Menos incertidumbre para el cliente. Más claridad para el servicio técnico.</p></div></div>
    </section>

    <section className="public-section border-y border-line bg-surface py-18 sm:py-22" id="que-es-nodo"><div className="public-container grid gap-10 lg:grid-cols-[0.82fr_1.18fr]"><div><p className="section-kicker">¿Qué es Nodo?</p><h2 className="section-title mt-3"><strong>Nodo</strong> documenta el proceso completo de una reparación.</h2><p className="mt-5 max-w-xl text-base leading-7 text-ink-secondary">No se limita a administrar órdenes. Su propósito es que cada decisión quede clara y cada etapa pueda consultarse después.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{connectedItems.map((item, index) => <div className="flex min-h-14 items-center gap-3 rounded-xl border border-line bg-surface-soft px-4 text-sm font-semibold text-ink" key={item}><span className="grid size-6 shrink-0 place-items-center rounded-full bg-accent text-[10px] font-bold text-white">{index + 1}</span>{item}</div>)}</div></div></section>

    <section className="public-section public-container py-18 sm:py-22" id="funcionalidades"><div className="max-w-3xl"><p className="section-kicker">Funciones con un propósito</p><h2 className="section-title mt-3">Herramientas concretas para problemas reales.</h2><p className="mt-4 text-base leading-7 text-ink-secondary">Cada función de <strong>Nodo</strong> busca reducir tareas repetitivas, conservar decisiones y darle contexto a cada reparación.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, title, description }) => <Card className="group border-line bg-surface-raised p-6 transition duration-200 hover:-translate-y-1 hover:border-accent hover:shadow-[0_12px_30px_rgb(var(--shadow-color)/10%)]" key={title}><span className="grid size-11 place-items-center rounded-xl bg-accent-soft text-accent"><Icon className="size-5" /></span><h3 className="mt-5 text-lg font-bold text-ink">{title}</h3><p className="mt-3 text-sm leading-6 text-ink-secondary">{description}</p></Card>)}</div><Card className="mt-4 grid gap-5 border-line bg-surface-soft p-6 sm:grid-cols-[auto_1fr] sm:items-start"><span className="grid size-11 place-items-center rounded-xl bg-accent-soft text-accent"><Wrench className="size-5" /></span><div><h3 className="text-lg font-bold text-ink">Cada reparación tiene su prioridad</h3><p className="mt-2 text-sm leading-6 text-ink-secondary">Un viaje próximo, el uso laboral del dispositivo, un repuesto difícil de conseguir, un diagnóstico complejo o una urgencia acordada cambian la forma de ordenar el trabajo. <strong>Nodo</strong> busca ayudar al técnico a organizar su tiempo real, no solamente una lista por fecha.</p></div></Card></section>

    <section className="public-section border-y border-line bg-brand-surface py-18 text-brand-contrast sm:py-22" id="como-funciona"><div className="public-container grid gap-10 lg:grid-cols-[0.72fr_1.28fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-cyan-300">¿Cómo funciona?</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Una reparación avanza como una secuencia conectada.</h2><p className="mt-5 text-base leading-7 text-brand-muted">La demostración muestra cómo una orden conserva recepción, diagnóstico, presupuesto, aprobación, reparación y entrega sin perder la historia entre una etapa y la siguiente.</p><p className="mt-5 text-sm font-semibold text-white">● Ingreso ── ● Diagnóstico ── ● Decisión ── ● Resultado</p></div><RepairFlowDemo /></div></section>

    <section className="public-section public-container grid gap-10 py-18 sm:py-22 lg:grid-cols-[0.9fr_1.1fr] lg:items-center" id="por-que-nodo"><div className="rounded-[1.5rem] border border-line bg-accent-soft p-7 sm:p-9"><Smartphone className="size-8 text-accent" /><h2 className="mt-6 text-3xl font-bold tracking-tight text-ink">Saber cómo entra. Saber qué se hace. Saber cómo sale.</h2><p className="mt-4 text-base leading-7 text-ink-secondary">Ese es el criterio que guía el diseño de la aplicación y la información que acompaña a cada orden.</p></div><div><p className="section-kicker">¿Por qué Nodo?</p><h2 className="section-title mt-3">Un punto donde personas, dispositivos y decisiones se conectan.</h2><p className="mt-5 text-base leading-7 text-ink-secondary">Un nodo conecta elementos diferentes. En esta aplicación vincula una persona, su dispositivo, un técnico, una orden, un diagnóstico, una decisión y una reparación.</p><p className="mt-4 text-base leading-7 text-ink-secondary">Pero la conexión más importante es la confianza. Cada etapa genera información, y <strong>Nodo</strong> intenta mantenerla unida para evitar incertidumbre.</p></div></section>

    <section className="public-section border-y border-line bg-surface py-18 sm:py-22" id="sobre-la-aplicacion"><div className="public-container grid gap-10 lg:grid-cols-[1.15fr_0.85fr]"><div><p className="section-kicker">Sobre la aplicación</p><h2 className="section-title mt-3"><strong>Nodo</strong> es un proyecto de software gratuito y sin fines de lucro.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-ink-secondary">Fue creado inicialmente para ayudar a organizar servicios técnicos alrededor de dos principios: transparencia para el cliente y simplicidad para quien realiza el trabajo. La aplicación sigue siendo el centro del proyecto.</p></div><div className="rounded-xl border border-line bg-surface-soft p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-accent">Desarrollado por</p><h3 className="mt-3 text-xl font-bold text-ink">Lada Elizabet Rodriguez</h3><p className="mt-1 text-sm font-semibold text-ink-secondary">Desarrolladora de software</p><p className="mt-4 text-sm leading-6 text-ink-secondary">Esta plataforma surge de observar un problema recurrente: la desconfianza, la comunicación fragmentada y falta de trazabilidad en reparaciones cotidianas.</p></div></div></section>

    <section className="public-section public-container py-18 sm:py-22" id="contactame"><div><p className="section-kicker">Contáctame</p><h2 className="section-title mt-3">Consultas, colaboración y desarrollo de software.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-ink-secondary">Podés escribirme por dudas sobre <strong>Nodo</strong>, reportes de bugs, propuestas de mejora o proyectos profesionales.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-[1fr_1fr]"><Card className="border-line bg-surface-raised p-6 sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.14em] text-accent">Desarrolladora</p><h3 className="mt-3 text-xl font-bold text-ink">Lada Elizabet Rodriguez</h3><p className="mt-1 text-sm font-semibold text-ink-secondary">Desarrolladora de software</p><p className="mt-5 flex items-start gap-3 text-sm text-ink-secondary"><MapPin className="mt-0.5 size-4 shrink-0 text-accent" />Ciudad de Formosa, provincia de Formosa, Argentina</p><div className="mt-6 grid gap-3"><ContactLink icon={Github} href="https://github.com/ladardrgz/ladardrgz" label="GitHub: @ladardrgz" external /><ContactLink icon={MessageCircle} href="https://wa.me/543705176505" label="Escribirme por WhatsApp · +54 3705 176505" external /><ContactLink icon={Mail} href="mailto:ladardrgz@gmail.com" label="Enviar correo · ladardrgz@gmail.com" /></div></Card><div className="grid gap-5"><Card className="border-line bg-surface-soft p-6"><h3 className="text-lg font-bold text-ink">Ayudá a mejorar <strong>Nodo</strong></h3><p className="mt-3 text-sm leading-6 text-ink-secondary">Podés contactarme para reportar fallos, sugerir mejoras, proponer funciones, consultar dudas o pedir orientación básica de uso. La atención personalizada relacionada con <strong>Nodo</strong> es sin costo, dentro de mis posibilidades.</p></Card><Card className="border-line bg-surface-raised p-6"><h3 className="text-lg font-bold text-ink">¿Necesitás desarrollar una solución?</h3><p className="mt-3 text-sm leading-6 text-ink-secondary">También realizo proyectos de software y desarrollo web.</p><a className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-lg border border-line bg-surface-soft px-4 text-sm font-bold text-accent transition-colors hover:border-accent" href="https://project-visibility.ladardrgz.workers.dev/" rel="noopener noreferrer" target="_blank"><Github className="size-4" />Digital Visibility Project <ArrowRight className="size-4" /></a></Card></div></div></section>
  </main><PublicFooter /></div>;
}

function ContactLink({ icon: Icon, href, label, external = false }: { icon: ComponentType<{ className?: string }>; href: string; label: string; external?: boolean }) { return <a className="inline-flex min-h-12 items-center gap-3 rounded-lg border border-line bg-surface-soft px-4 text-sm font-semibold text-ink transition-colors hover:border-accent hover:text-accent" href={href} rel={external ? "noopener noreferrer" : undefined} target={external ? "_blank" : undefined}><Icon className="size-4 shrink-0 text-accent" /><span className="min-w-0 break-words">{label}</span></a>; }